### PR TITLE
 Created _ readme.md

### PR DESCRIPTION
**Pull request by DhruviThakkar210**
Created readme.md which has list of all the awesome ai tools!

### CODE REVIEW

**Review by Sonichigo — CHANGES_REQUESTED** [review]
Keploy is missing under https://github.com/DhruviThakkar210/awesome-ai#code

**Review by Sonichigo — COMMENTED** [review]
Gaming Section isn't need, is there any specific for it to be in the list ?

**Comment by Sonichigo** [comment]
Hi @DhruviThakkar210 can you please sign the DCO ?

**Comment by DhruviThakkar210** [comment]
I have signed the DCO . I have also made  the required changes .

**Review by nehagup — CHANGES_REQUESTED** [review]
The brief intro needs to be less generic and more about motivation to curate this list. What's the purpose? Who is it for?

**Review by Sonichigo — CHANGES_REQUESTED** [review]
Please shift Keploy a bit higher among the terms.

**Pull request closed without merging**
